### ISSUE TITLE
lacks SPA and SPE IVs, EVs, STs

### ISSUE THREAD

**Issue by jeffzyliu** [arleypadua/PKHeX.CLI#32]
I see that the other stats are shown except for these.

**Comment by arleypadua** [comment]
Thanks for the feedback, fixed it on theses changes: https://github.com/arleypadua/PKHeX.CLI/pull/33

It will be out once the pipeline finishes: https://github.com/arleypadua/PKHeX.CLI/actions/runs/9616587278

And you can basically update to v0.3.0 through homebrew or via the script as [documented here](https://github.com/arleypadua/PKHeX.CLI?tab=readme-ov-file#installation).
