### ISSUE TITLE
Corrupted file

### ISSUE THREAD

**Issue by joebudda** [arleypadua/PKHeX.CLI#47]
Hi, 

I used pkhex github to edit my pokemons EVs on pokemon Eternal X romhack and when I reopened it it says the file is corrupted. not sure what to do please help

**Comment by arleypadua** [comment]
Hey, can you share with me your original safe file and what was expected? 

I may be able to find some time this weekend to investigate

**Comment by arleypadua** [comment]
Ah, sorry.. just realized that you're editing a save from a ROM hack, which is not really supported.

Only official saves are supported

**Comment by joebudda** [comment]
Is there any way to change that? so sad :(

**Comment by arleypadua** [comment]
Unfortunately not, this program relies on PKHeX.Core, which is the ultimate source for the support: https://github.com/kwsch/PKHeX

Have you trying editing it straight with PKHeX on Windows?

**Comment by joebudda** [comment]
I am unfortunately on mac so I cant access it. Ive tried many times with winebottler but cant figure it out. I am not very skilled with these kinds of things

**Comment by arleypadua** [comment]
I don't know if the save files are compatible honestly, I did try loading/expiring a Pokemon X save file and it worked as expected. 

So I guess there's not much I can do here.

**Comment by arleypadua** [comment]
Just for a proper closure, I tried editing a Pokemon X save and also loaded that into a game and it also worked, so, indeed, the ROM hack is not supported, unfortunately.
